export const SELECTED_QUESTION = 'SELECTED_QUESTION'
export const SELECTED_ANSWER = 'SELECTED_ANSWER'

export const CHANGE_OLD_PRECIS = 'CHANGE_OLD_PRECIS'
export const CHANGE_NEW_PRECIS = 'CHANGE_NEW_PRECIS'

export const SET_SIDEBAR_ELEMENT = 'SET_SIDEBAR_ELEMENT'

export const SET_BOOK_RATING = 'SET_BOOK_RATING'

export const SAVE_OPENED_BOOK_ID = 'SAVE_OPENED_BOOK_ID'

export const CHANGE_BLIND_MODE = 'CHANGE_BLIND_MODE'

export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS'
export const SAVE_THEME_SETTINGS = 'SAVE_THEME_SETTINGS'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'

export const SET_BOOK_SCROLL = 'SET_BOOK_SCROLL'
export const SET_BOOK_CATEGORY = 'SET_BOOK_CATEGORY'

export const SET_NEW_BOOK_PRECIS = 'SET_NEW_BOOK_PRECIS'
export const SET_OLD_BOOK_PRECIS = 'SET_OLD_BOOK_PRECIS'
export const SET_BOOK_MENU = 'SET_BOOK_MENU'
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_SEARCH_BOOK = 'SET_SEARCH_BOOK'
export const SET_FILTERED_BOOKS = 'SET_FILTERED_BOOKS'

export const SET_MAIN_ALL_BOOKS = 'SET_MAIN_ALL_BOOKS'
export const SET_MAIN_HUMANITARIES_BOOKS = 'SET_MY_HUMANITARIES_BOOKS'
export const SET_MAIN_TECHNICAL_BOOKS = 'SET_MY_TECHNICAL_BOOKS'
export const SET_MAIN_MEDICAL_BOOKS = 'SET_MY_MEDICAL_BOOKS'

export const SET_MY_ALL_BOOKS = 'SET_MY_ALL_BOOKS'
export const SET_MY_HUMANITARIES_BOOKS = 'SET_MY_HUMANITARIES_BOOKS'
export const SET_MY_TECHNICAL_BOOKS = 'SET_MY_TECHNICAL_BOOKS'
export const SET_MY_MEDICAL_BOOKS = 'SET_MY_MEDICAL_BOOKS'

export const GET_GENERAL_PROGRESS = 'GET_GENERAL_PROGRESS'
export const GET_READED_PROGRESS = 'GET_READED_PROGRESS'
export const GET_IREAD_PROGRESS = 'GET_IREAD_PROGRESS'
export const GET_TEST_QUESTIONS = 'GET_TEST_QUESTIONS'
export const SET_BOOK_INFO = 'SET_BOOK_INFO'
export const SET_ANSWER = 'SET_ANSWER'
export const LOAD_BOOK_VIDEO = 'LOAD_BOOK_VIDEO'

export const SET_TEST_FINISHED = 'SET_TEST_FINISHED'